version: "3.8"

services:
  # Nginx webserver service
  nginx:
    image: nginx:1.18
    ports:
      - 8282:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - php

  # PHP-FPM service
  php:
    build: ./.docker/php
    volumes:
      - ./src:/var/www/php
    command: sh -c "php ./wsserver.php start -d && php-fpm"