version: '3.8'

services:
  # Nginx webserver service
  nginx:
    image: nginx:1.18
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP-FPM service
  php:
    build: ./.docker/php
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    depends_on:
      mysql:
        condition: service_healthy

  #MySQL service
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mojeHeslo.123
      # MYSQL_1ROOT_HOST: "%"
      MYSQL_USER: xpitkakester
      MYSQL_PASSWORD: mojeHeslo.123
      MYSQL_DATABASE: z3_webte2
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/mysql.cnf
      - ./.database:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
  
  # phpMyAdmin interface
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
# Volumes
volumes:
  mysqldata:
