openapi: 3.0.3
info:
  title: University Management API
  description: This API manages timetable and end assignment projects for university courses.
  version: 1.0.0
servers:
  - url: http://localhost/api
paths:
  /timetable:
    get:
      summary: Retrieve all timetable entries
      responses:
        '200':
          description: Successfully retrieved list of timetable entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimetableEntry'
    post:
      summary: Create a new timetable entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimetableEntry'
      responses:
        '201':
          description: Successfully created a new timetable entry

  /timetable/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: Unique identifier of the timetable entry
    delete:
      summary: Delete a specific timetable entry
      responses:
        '200':
          description: Successfully deleted the timetable entry
    put:
      summary: Update a specific timetable entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimetableEntry'
      responses:
        '200':
          description: Successfully updated the timetable entry

  /curlTimetable:
    get:
      summary: Fetch timetable data via curl
      responses:
        '200':
          description: Successfully fetched and returned timetable data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurlResponse'

  /endAssigment:
    get:
      summary: Retrieve all end assignment projects
      responses:
        '200':
          description: Successfully retrieved list of end assignment projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EndAssignmentProject'

  /endAssigment/{detailNum}/{pracovisko}:
    parameters:
      - in: path
        name: detailNum
        schema:
          type: integer
        required: true
        description: Unique identifier of the assignment detail
      - in: path
        name: pracovisko
        schema:
          type: integer
        required: true
        description: Unique identifier of the workplace or department
    get:
      summary: Fetch annotation for a specific end assignment project
      responses:
        '200':
          description: Successfully fetched annotation for the end assignment project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnnotationResponse'

components:
  schemas:
    TimetableEntry:
      type: object
      properties:
        id:
          type: integer
        day:
          type: string
        type:
          type: string
        name:
          type: string
        classroom:
          type: string
      required:
        - day
        - type
        - name
        - classroom

    CurlResponse:
      type: object
      properties:
        message:
          type: string
        subjects:
          type: array
          items:
            $ref: '#/components/schemas/TimetableEntry'

    EndAssignmentProject:
      type: object
      properties:
        typ:
          type: string
        nazov_temy:
          type: string
        veduci_prace:
          type: string
        garantujuce_pracovisko:
          type: string
        program:
          type: string
        zameranie:
          type: string
        detail:
          type: string
        obsadenost:
          type: string
        pracovisko:
          type: integer
      required:
        - typ
        - nazov_temy
        - veduci_prace
        - garantujuce_pracovisko

    AnnotationResponse:
      type: object
      properties:
        message:
          type: string
        annotation:
          type: string
